dist: bionic
addons:
  apt:
    source:
    - docker-bionic
    packages:
    - docker
services:
- docker
env:
  global:
  - DH_ORG: tokendconto
  - DH_IMAGE_NAME: admin-panel
  - PROJECT: tokend
  - IMAGE_NAME: admin-panel-conto
  - secure: QvuyMRbFHtcSs0iV286/LJl+r+/3yqa+hlGlEIrKEGb/4XiTrRTL1csM3PUE5jArGLgW7pbVrMfyBGyEFLZobnO41/YgNN9MzfcGnbT93aoJQOVUhHuKaWTAVHldNzFDbq48kM5314g42/G8/A8bEv/QLZZfIqI5UW43sDO3Kthurog24yklft6AzCg39bplZ6M+0cHRLEiFKwMPZSnk9o+2jrSXJcVisFH6Q6pmkn0clHq4pbzy8p1NIYqrSmVoa5DYDA2WUIyNsW0wPLK3Uql3Ah5E5jQ5KaWLezY98mIsbK/bqLHd8LMyjl/FQEnSvur8l89BXkIFQnbLty/Z76tCTsADV/Emav9SfTRIeMmb8caCqJvmJZO1iCvtobDapFg9/iU66gIofqNYS/kkkRvCeOCIACKJAyW7tS9ryg115F5188gr6GkS+T0fq0Giy1fW9P4j/Jar3UgRSD8bEmEPe0F2OZg+1kpLvaLa5oHz4IoH0K9phGMWb7L6b39/wntTBFSoTUegJ9qPCoQ4DWOAToIndlT6aDVkSBOZftgcx5RR+QeceHFFmiW6h4YI3Tujutgku0ht7/2JE/0jLjHHEnGg+3AYKSXk9t67ZF+ukjwWJgpZfAHgz3lzqhVbk1Pm2yF4gSm8LvAQdXJe+N6eVkFs40GhEmE9ROeM8/8=
  - secure: GzWDzcRGSGNaGqYHqAYC1BWvdg3RaUoOpWqzUvHDg08Pb0qIS4dfPEsU/grA8ea9x4sxtd6Yc4ourhpqpVdxmGLkL97itIPz1iWyrZ3h9nNmabmEga0/mOEGBrxUypiysS/xRAoRFta+Qq4MAugwjLalxCKIrJWDCHSw/odsOSjTQcsB/n3UfJu4Sk5IWK0Adq0Rl88BWdnNVxgGYxDKn9rsA8EEDapz2s0IUT4brZ0HideKDoDRZ2qAhkgllPLCv5NVNGoYe0ZhlVhRDpLbVccneZgl1Kr3Pt0YVv29OmwmLzyStb5zRXRd/DdhWgtNUyJ3DGoTNExcuSaqcrcmoClR88Se3IaNESvjN6QCe7w5T8alS2PCQLDTAO4vB74s1XB1jhF9chnB5+GP3NzWDZR0r/pcv+M4b9qeV/J+0tHgWn9znGd6jiV0flNlbS/yFbv47rO4SReTSGyEuNzWD9lDyjJ0A7xqRlQadZD6bHNQaBA08Z9mv6a+JI2aXT9/ESKFA2YKjLAFpcCi31JXQRZCgvzEQ3OolJ/hYEF+CIBILCz5z68lSwPgyWD9hBrIxCPJRDw4Z639Cs5E6RWyeoq7aLddZ3maDnOdqwgmnPUbzD4h6BgneUoLvbDltSSwerwOJDA1D3SoTzrl0XxXxkvl1epEKzUcxlgdWQutuug=
  - secure: iCjWHt12y/zmMEdTExb6t7Qah4MmTk4vH0rytwL5STt9ESkU5U5gi8hWSjRRGHwfIqU9SL+0CDZ61QuX97BVrqqLtSZlroRSsr8oWihUDnXOt7nTmkB9GMCvRgUnEOerF52N2CA6pOSpuJx0ZwkaesK1RLkLEVc1cNe4QMfJ3FVycxbzXoaFPwvJb3t4gdD7jW7R6R3haV37enzkqFeQbZquLIAnwcDqtGltIc135VV3Pw0T4ReY8LqhzeBmcLPrW6zdJDRYwsQJfsTdd+q/D8csJxJjoi6e+SSmvIv3snGbdBUNIe3khAMeKU9NXteZ4nPNdxjRKXpSYlN8127xflnwIYdLwVaqMoERgmHY8Vd3ppKeHrYCOGurHKs9MOwQMmjJ1F3I7iF8a/BMVtMssVeONHzURCNAnotnn3m+ONs4N1ZxNuFIpzX/7NfuGndb6NuVPoXezn91zyDKKUPdD0Tqju2ukcvUG43Z+Iw4+Z0+ngPg4ixVyoOVG9ovQJbXRbLYyDni6khIqGqCcjKiI4Wn1O6vEvdTt2Cy3da6bEbAm/fK/XLmwFZvRhjRAI0bVmdxJqDaFiZ30WxDAegdMr7vm99wwX6yAP/U3S8+7+EgTa5Eo8SjlaJaAYgj8scNMIBRUYth6HwFg9FC0MVs5jWloMKwlWBOZeMxUTfZep8=
  - secure: aKauCcBwpXXY5DZv7GH6f0unfSrcPF/0EIGQGrFaZjK1VAMmhdpaHpPeAsy0/MxjJjV+/IBejrqUeE8OiN5j+pOFGvzZbcPY1Nb950Irt4CndfXTdkYref1MJSjdD4T3qWNSEUyaKA6I/eCT4yzOUwvOcRoYyG81Faah8hwYnZNOenz7FFFoN3nKweimsbIIkUbjTkqyxj6DCjoNlFbKpMwpHrPUQcgFtHRmeeHmHC9N7ho2S+2Pos2FlYLbJ/3354mMLXtI6M66ZUXUtEmIM6SwQBNDM/JrBzW7iifZDj7oU6P/n1yj1SqFm/dtmbeOtgNj3NuoqqTTufRz7ue87D/yXOhb7mGeqtA/VGAukkp2oNh8vH0+az/VKtvcOUYNG+4ur7XNEPRCmK51iyuntXOeslqhQx7LHWxxreTnT/GH/GUCPsp2OHiGuIDM99d7r9TjFX3pycZis3x3g1GSAJzufWvohuKE2k2pPj23f6F1LU9EjJk+RgIYtTTiPWC4o8Lq+m51EXrgxlNYyOMECKdN29W2yBd3MF5q/FAAq+igzyyxg33/pQLyO9BvYzHHd8bbJFAFseTSqOmRdKeS/uw5/imuZ7G5T+y4DqQ9ki0Q8S8KCNPkSONXGNvAAedA93G7lsag7PRlT8j3WM1whThrtrxUB2fwtEDgUsCtrKo=
script:
- export IMAGE_TAG=$(test -z $TRAVIS_TAG && echo $TRAVIS_COMMIT || echo $TRAVIS_TAG)
- docker build --build-arg BUILD_VERSION="$IMAGE_TAG" -t $DH_ORG/$DH_IMAGE_NAME:$IMAGE_TAG
  .
before_deploy:
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
- echo "$GITLABREG_PASSWORD" | docker login -u "$GITLABREG_USERNAME" --password-stdin
  registry.gitlab.com
- docker tag $DH_ORG/$DH_IMAGE_NAME:$IMAGE_TAG registry.gitlab.com/$PROJECT/docker-registry/$IMAGE_NAME:$IMAGE_TAG
deploy:
- provider: script
  script:
  - docker push $DH_ORG/$DH_IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
    tags: true
- provider: script
  script:
  - docker push registry.gitlab.com/$PROJECT/docker-registry/$IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
    tags: false
